version: '3.8'

services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    ports: 
      - 9200:9200
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic
  
  app:
    build: '.'
    container_name: app
    environment: 
      - ELASTICSEARCH_HOST: elasticsearch
      - ELASTICSEARCH_PORT: 9200
    networks: 
      - elastic

volumes: 
  data:
    driver: local

networks: 
  elastic:
    driver: bridge